name: Release

on:
  pull_request:
    types:
      - closed
    branches-ignore:
      - development
      - staging
      - main
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR to ${{ github.ref }} was merged
