name: 2023 - Manual Deployment

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: First 7 digits of the commit_id you want testing
        required: false
      
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pause for approval in PRO
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: carlos-tapasco
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        issue-body: "Please approve or deny the deployment of version v1.3.5."
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
        
    - name: Check if var exists
      run: |
        if [ -z "${{ github.event.inputs.commit_id }}" ]; then
          echo "Input variable not set"
          .bin/deploy_2023.sh $GITHUB_REF_NAME $GITHUB_SHA
        else
          echo "Input variable is set to '${{ github.event.inputs.commit_id }}'"
          .bin/deploy_2023.sh $GITHUB_REF_NAME ${{ github.event.inputs.commit_id }}
        fi
      
    #- name: Configure AWS credentials
    #  uses: aws-actions/configure-aws-credentials@v1-node16
    #  with:
    #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    aws-region: us-east-1

    #- name: Deploy immediately with AWS CodeDeploy
    #  run: .bin/deploy_2023.sh $GITHUB_REF_NAME $GITHUB_SHA
