name: 2023 - Build

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - staging
      - master

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    concurrency:
      group: 2023-build-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1.5.3

    - name: Building and pushing the Docker image
      run: |
        .bin/build_2023.sh $GITHUB_REF_NAME $GITHUB_SHA