name: artifact

on: [push]

env:
  ARTIFACT_NAME: file1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Check code"
        uses: actions/checkout@v2
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: . 
