name: Branch testing

on:
  push:
    branches:
      - feat-2

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Output variables
      run: |
        echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT