name: Branch testing

on:
  push:
    branches:
      - feat-2

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set output variables
      id: first-job-step-2
      run: |
        echo "MY_VAR=Salida" >> $GITHUB_ENV

    - name: Display output variable in Workflow Summary
      run: |
        echo ${{ env.MY_VAR }} >> $HOME/results.txt