name: ci-cd

on: 
  workflow_dispatch:

env:
  ARTIFACT_NAME: hello.py

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repo"
        uses: actions/checkout@v2
      - name: "Run the script"
        run: python ${{ env.ARTIFACT_NAME }}

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repo"
        uses: actions/checkout@v2
      - name: "Create artifact"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
