name: Manual Build and Deploy - DEV (2023)

on:
  workflow_dispatch:
    inputs:
      pr_commit_id:
        description: 'Enter the seven digit commit ID of the closed pull request in the develop branch'
        required: true

jobs:
  get-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get a list of closed pull requests
        id: get_pull_requests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const github = require('@actions/github');
            const pulls = await github.pulls.list({
              owner,
              repo,
              state: 'closed',
              base: 'master',
              per_page: 10
            });
            return JSON.stringify(pulls.data);

      - name: Print Pull Requests
        run: |
          echo "${{ steps.get_pull_requests.outputs.result }}"
          echo "Manual commit ID ${{ inputs.pr_commit_id }}"