name: Release to PRO

on:
  pull_request:
    types:
      - closed
    branches:
      - production
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR to ${{ github.ref }} was merged
