name: Sync CI/CD Branches
on:
  push:
    branches:
      - main
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 11

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          PULL_REQUEST_TITLE: "sync: {FROM_BRANCH} to {TO_BRANCH} - commit: ${{ github.ref }}"
          PULL_REQUEST_BODY: "sync-branches: New code has just landed in {FROM_BRANCH} so let's bring {TO_BRANCH} up to speed!"
          #PULL_REQUEST_IS_DRAFT: "false"
          CONTENT_COMPARISON: "true"
          REVIEWERS: '["cartapas"]'
          #TEAM_REVIEWERS: []
        
      - name: Output PR data
        run: |
          echo "PR URL: ${{ steps.pull.outputs.PULL_REQUEST_URL }}"
          echo "PR NUMBER: ${{ steps.pull.outputs.PULL_REQUEST_NUMBER }}"